FROM node:24-slim

# Install minimal deps for Next.js (optional but safer)
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy only dependency files
COPY ./nextjs_code/package.json ./package.json
COPY ./nextjs_code/package-lock.json ./package-lock.json

# Recommended npm settings for dev containers
RUN npm set legacy-peer-deps true \
 && npm set fund false \
 && npm set audit false \
 && npm set progress=false \
 && npm set prefer-offline=true

# Install deps inside container
# RUN rm -f package-lock.json \ && npm install --package-lock-only \ && npm install
#
# # Now copy project files (safe because node_modules is already installed)
# COPY ./nextjs_code/tsconfig.json ./tsconfig.json
# COPY ./nextjs_code/postcss.config.mjs ./postcss.config.mjs
# COPY ./nextjs_code/tailwind.config.ts ./tailwind.config.ts
# COPY ./nextjs_code/next.config.ts ./next.config.ts
# COPY ./nextjs_code/public ./public
# COPY ./nextjs_code/src ./src

EXPOSE 3000

CMD ["npm", "run", "dev"]
