FROM node:24-bullseye

RUN apt-get update && apt-get install -y libc6

WORKDIR /app

RUN npm install -g pnpm && corepack enable

ENV NEXT_PUBLIC_MEDIA_DOMAIN="http://localhost"
COPY ./nextjs_code/pnpm-lock.yaml ./nextjs_code/package.json ./
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store pnpm install

COPY ./nextjs_code/public/ ./nextjs_code/src/ ./nextjs_code/eslint.config.mjs \
  ./nextjs_code/next.config.ts ./nextjs_code/postcss.config.mjs ./nextjs_code/tailwind.config.ts \
  ./nextjs_code/tsconfig.json ./

EXPOSE 3000
CMD ["pnpm", "dev"]
