services:
  db:
    image: postgres:18-alpine
    env_file: .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: chino-backend:prod
    build:
      context: ./backend
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env.dev
    volumes:
      - ./backend:/app:Z
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    dns:
      - 1.1.1.1
      - 8.8.8.8

  frontend:
    image: chino-frontend:dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file: .env.dev
    volumes:
      - ./frontend/nextjs_code/src:/app/src
      - ./frontend/nextjs_code/public:/app/public
      - ./frontend/nextjs_code/next.config.ts:/app/next.config.ts
      - ./frontend/nextjs_code/tsconfig.json:/app/tsconfig.json
      - ./frontend/nextjs_code/postcss.config.mjs:/app/postcss.config.mjs
      - ./frontend/nextjs_code/tailwind.config.ts:/app/tailwind.config.ts
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  node_modules_cach:
