services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:

    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/django_code:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
