
services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    expose:
      - "5432"

  backend:
    build: ./backend/
    command: gunicorn chinocafe.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - internal
    expose:
      - "8000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - internal
    expose:
      - "3000"

  nginx:
    build: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: >
      sh -c 'certbot certonly --webroot --webroot-path=/var/www/certbot
      --email mohamadalinaghian@gmail.com --agree-tos --no-eff-email
      -d chinocafe.ir -d www.chinocafe.ir'

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
