services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

    expose:
      - "5432"

  backend:
    build: ./backend/
    command: gunicorn django_code.config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db

    expose:
      - "8000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend
    expose:
      - "3000"



volumes:
  postgres_data:

