from __future__ import annotations

from decimal import Decimal

from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from persiantools.jdatetime import JalaliDate


class DailyFinancialReport(models.Model):
    """
    Pure data model for daily financial snapshots.
    All calculations done in FinancialReportService.
    """

    report_date = models.DateField(
        _("Report date"), unique=True, db_index=True, default=timezone.now
    )

    # Revenue tracking
    total_revenue = models.DecimalField(
        _("Total revenue"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )
    pos_total = models.DecimalField(
        _("POS total"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )
    cash_total = models.DecimalField(
        _("Cash total"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )
    card_transfer_total = models.DecimalField(
        _("Card transfer total"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )

    # Expense tracking
    purchase_expenses = models.DecimalField(
        _("Purchase expenses"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )
    operational_expenses = models.DecimalField(
        _("Operational expenses"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )
    total_cogs = models.DecimalField(
        _("Total COGS"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )

    # Profit calculation
    gross_profit = models.DecimalField(
        _("Gross profit"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )
    net_profit = models.DecimalField(
        _("Net profit"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )

    # Discrepancy tracking
    pos_discrepancy = models.DecimalField(
        _("POS discrepancy"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )
    cash_discrepancy = models.DecimalField(
        _("Cash discrepancy"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )
    card_to_card_discrepancy = models.DecimalField(
        _("Card to card discrepancy"),
        max_digits=12,
        decimal_places=4,
        default=Decimal("0"),
    )

    # Report metadata
    generated_by = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Generated by"),
    )
    generated_at = models.DateTimeField(
        _("Generated at"),
        auto_now_add=True,
    )
    is_finalized = models.BooleanField(
        _("Is finalized"),
        default=False,
        help_text=_("Finalized reports cannot be modified"),
    )
    notes = models.CharField(_("Notes"), blank=True, default="", max_length=512)

    @cached_property
    def jalali_report_date(self) -> str:
        return JalaliDate(self.report_date).strftime("%c", locale="fa")

    class Meta:
        verbose_name = _("Daily Financial Report")
        verbose_name_plural = _("Daily Financial Reports")
        ordering = ("-report_date",)
        indexes = [
            models.Index(fields=["report_date"]),
            models.Index(fields=["is_finalized"]),
        ]

    def __str__(self) -> str:
        return f"Financial Report - {self.jalali_report_date}"
