# Generated by Django 5.2.3 on 2025-07-24 13:17

import apps.utils.upload_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Title')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.utils.upload_path.menu_thumbnail_path, verbose_name='Thumbnail')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('images', models.ManyToManyField(blank=True, related_name='menu_items', to='utils.image', verbose_name='Extra Images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menus', to='menu.menucategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
