# apps/sale/tests/factories/daily_financial_report.py
"""
Factory for DailyFinancialReport model.

Generates test data for daily financial summaries with revenue, expenses, and profits.
"""

from decimal import Decimal

import factory
from apps.sale.models import DailyFinancialReport
from django.utils import timezone


class DailyFinancialReportFactory(factory.django.DjangoModelFactory):
    """
    Factory for creating DailyFinancialReport instances.

    Generates realistic financial reports with:
    - Revenue breakdown by payment method
    - Expense tracking
    - Profit calculations
    - Discrepancy tracking

    Note: In production, reports are generated by FinancialReportService,
    but this factory is useful for testing report-related functionality.
    """

    class Meta:
        model = DailyFinancialReport

    report_date = factory.LazyFunction(lambda: timezone.now().date())

    # Revenue tracking
    total_revenue = factory.Faker(
        "pydecimal",
        left_digits=8,
        right_digits=4,
        positive=True,
        min_value=500000,
        max_value=5000000,
    )

    @factory.lazy_attribute
    def pos_total(self):
        """POS typically represents 40% of revenue."""
        return self.total_revenue * Decimal("0.4")

    @factory.lazy_attribute
    def cash_total(self):
        """Cash typically represents 35% of revenue."""
        return self.total_revenue * Decimal("0.35")

    @factory.lazy_attribute
    def card_transfer_total(self):
        """Card transfers represent the remaining 25%."""
        return self.total_revenue * Decimal("0.25")

    # Expense tracking
    @factory.lazy_attribute
    def purchase_expenses(self):
        """Purchase expenses are typically 30% of revenue."""
        return self.total_revenue * Decimal("0.3")

    operational_expenses = factory.Faker(
        "pydecimal",
        left_digits=6,
        right_digits=4,
        positive=True,
        min_value=50000,
        max_value=200000,
    )

    @factory.lazy_attribute
    def total_cogs(self):
        """COGS typically represents 35% of revenue."""
        return self.total_revenue * Decimal("0.35")

    # Profit calculation
    @factory.lazy_attribute
    def gross_profit(self):
        """Gross profit = Revenue - COGS."""
        return self.total_revenue - self.total_cogs

    @factory.lazy_attribute
    def net_profit(self):
        """Net profit = Gross profit - Operational expenses."""
        return self.gross_profit - self.operational_expenses

    # Discrepancy tracking (default to zero)
    pos_discrepancy = Decimal("0")
    cash_discrepancy = Decimal("0")
    card_to_card_discrepancy = Decimal("0")

    # Report metadata
    generated_by = factory.SubFactory(
        "apps.user.tests.factories.AccountFactory",
        is_staff=True,
    )
    is_finalized = False
    notes = factory.Faker("sentence", nb_words=10)


class FinalizedDailyFinancialReportFactory(DailyFinancialReportFactory):
    """
    Factory for finalized financial reports.

    Finalized reports cannot be modified.
    """

    is_finalized = True


class ReportWithDiscrepanciesFactory(DailyFinancialReportFactory):
    """
    Factory for reports with payment discrepancies.

    Simulates situations where actual counted amounts differ from system totals.
    """

    @factory.lazy_attribute
    def pos_discrepancy(self):
        """POS short by 2% (negative discrepancy)."""
        return self.pos_total * Decimal("-0.02")

    @factory.lazy_attribute
    def cash_discrepancy(self):
        """Cash over by 1% (positive discrepancy)."""
        return self.cash_total * Decimal("0.01")

    # No discrepancy for card transfers
    card_to_card_discrepancy = Decimal("0")
